- name: My first play
  hosts: servers
  tasks:

    - name: Print message
      ansible.builtin.debug:
        msg: CONNECTED!

    - name: Install common tools 
      become: yes
      become_method: sudo
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - screenfetch
          - fortune 


